services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hichuru/jaksel-house-price-predictor:latest
    container_name: jaksel-house-price
    restart: unless-stopped
    ports:
      - 5000:5000